<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Ejder.Core\Ejder.Core.csproj" />
    <ProjectReference Include="..\Ejder.Infrastructure\Ejder.Infrastructure.csproj" />
    <ProjectReference Include="..\Ejder.Domain\Ejder.Domain.csproj" />
    <ProjectReference Include="..\Ejder.Application\Ejder.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
